### ISSUE TITLE
[Question] MLBB API

### ISSUE THREAD

**Issue by jackvonhouse** [p3hndrx/MLBB-API#11]
Hi, I'm read your [post](https://www.reddit.com/r/MobileLegendsGame/comments/e71wnm/mlbb_playerstats_api/) on the Reddit from 3-4 years ago.

Have you any success finding an API beside `mapi.mobilelegends.com/hero/list` and `mapi.mobilelegends.com/hero/detail`?

I also saw `mapi.mobilelegends.com/legends/area` in the comments, but it doesn't return anything.

**Comment by p3hndrx** [comment]
Unfortunately, this is it.
You've reached the end of the road when it comes to APIs from MLBB.

**Comment by jackvonhouse** [comment]
@p3hndrx 3 years later you haven't even tried to find new APIs?
And what about `mapi.mobilelegends.com/legends/area`?
Are you getting empty data too?

**Comment by p3hndrx** [comment]
there are a half dozen unofficial, fan-supported APIs, but nothing from Moonton that I havent already explored and used in one bot or another..

I have been developing MLBB modules for about 6 years, and this is all there is.

mapi is being deprecated (as of 2 years ago).
and it requires a key to query

I work with the team that supports Harper, which is about as close of a public API available.
Sorry that isnt the answer you are looking for.

**Comment by jackvonhouse** [comment]
> I work with the team that supports Harper, which is about as close of a public API available.

It's interesting because it allows to get player data with rank and other info. Can you share API endpoint to send a request to get such data?

**Comment by p3hndrx** [comment]
Unfortunately, I cannot grant access to this API.
It is proprietary.

**Comment by jackvonhouse** [comment]
That's sad.. But thanks for the quick response. Good luck!
