### ISSUE TITLE
Scraping from mlbb wiki

### ISSUE THREAD

**Issue by arkarwine** [p3hndrx/MLBB-API#7]
[Suggestion] I am no mean professional but scraping the datasets from mlbb wiki rather than manually scraping them might make your life a whole lot easier. Although for many years players had been requesting for an official api mlbb has not yet provided one and doesn't seems like they will anytime now. Lefting us with the only choice to scrape from the wiki. I will work on the scraper if I have free time and I wanted to know if you have anything to say about it.

**Comment by p3hndrx** [comment]
As you can imagine, scraping from Wiki has its own problems... particularly with validity and keeping it up-to-date.
although i do maintain this API manually, it is accurate in so far as a person physically checks the equipment stats and matches them with the API data, then updates the repo to reflect that...
